# Generated by Django 3.0.7 on 2020-07-02 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_call_test_1', '0002_auto_20200702_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_call_array',
            name='voice_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
