# Generated by Django 3.0.7 on 2020-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_call_test_1', '0003_auto_20200702_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_call_array',
            name='receiver_numer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='voice_call_array',
            name='sender_number',
            field=models.IntegerField(blank=True),
        ),
    ]
