# Generated by Django 3.0.7 on 2020-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_call_test_1', '0004_auto_20200702_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_call_array',
            name='receiver_numer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voice_call_array',
            name='sender_number',
            field=models.IntegerField(),
        ),
    ]
