# Generated by Django 3.0.6 on 2020-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_call_test_1', '0005_auto_20200702_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice_call_array',
            name='id',
        ),
        migrations.AlterField(
            model_name='voice_call_array',
            name='sender_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
